export const movies = [
  {
    id: 1,
    image: "/assets/swashank-redemption.jpg",
    title: "The Shawshank Redemption",
    description:
      "A banker convicted of uxoricide forms a friendship over a quarter century with a hardened convict, while maintaining his innocence and trying to remain hopeful through simple compassion.",
    genre: "Drama",
    duration: "2h 5m",
    release: 2012,
    rating: [],
    ratingQty: 0,
    director: "Frank Darabont",
    actors: "Marlon Brando, James Caan, Robert Duvall, Al Pacino, Albert S. Ruddy",
    wishlist: false,
  },
  {
    id: 2,
    image: "/assets/the-.jpg",
    title: "The Godfather",
    description:
      "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    genre: "Crime",
    duration: "2h 55m",
    release: 1972,
    rating: [],
    ratingQty: 0,
    director: "Francis Ford Coppola",
    actors: "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler, Clancy Brown",
    wishlist: false,
  },
  {
    id: 3,
    image: "/assets/intersteller.jpg",
    title: "Interstellar",
    description:
      "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
    genre: "Sci-fi",
    duration: "1h 55m",
    release: 1998,
    rating: [],
    ratingQty: 0,
    director: "Christopher Nolan",
    actors: "Matthew McConaughey, Jessica Chastain, Ellen Burstyn, Timothée Chalamet, Collette Wolfe",
    wishlist: false,
  },
  {
    id: 4,
    image: "/assets/Like-star-on-earth.jpg",
    title: "Like Stars on Earth",
    description:
      "An eight-year-old boy is thought to be a lazy trouble-maker, until the new art teacher has the patience and compassion to discover the real problem behind his struggles in school.",
    genre: "Family",
    duration: "2h 23m",
    release: 2001,
    rating: [],
    ratingQty: 0,
    director: "Steve McQueen",
    actors: "Aamir Khan, Vipin Sharma, Darsheel Safary, Tisca Chopra, Lalitha Lajmi",
    wishlist: false,
  },
  {
    id: 5,
    image: "/assets/12-years-a-slave.jpg",
    title: "12 Years a Slave",
    description:
      "In the antebellum United States, Solomon Northup, a free black man from upstate New York, is abducted and sold into slavery.",
    genre: "Biography",
    duration: "2h 14m",
    release: 2013,
    rating: [],
    ratingQty: 0,
    director: "Steve McQueen",
    actors: "Michael Fassbender, Vipin Sharma, Darsheel Safary, Tisca Chopra, Lalitha Lajmi",
    wishlist: false,
  },
  {
    id: 6,
    image: "/assets/grave-of-the-fireflies.jpg",
    title: "Grave of the Fireflies",
    description: "A young boy and his little sister struggle to survive in Japan during World War II.",
    genre: "Animation",
    duration: "2h 43m",
    release: 1994,
    rating: [],
    ratingQty: 0,
    director: "Isao Takahata",
    actors: "Tsutomu Tatsumi, Ayano Shiraishi , Yoshiko Shinohara , Akemi Yamaguchi,  Masayo Sakai",
    wishlist: false,
  },
  {
    id: 7,
    image: "/assets/coco.jpg",
    title: "Coco",
    description:
      "Aspiring musician Miguel, confronted with his familys ancestral ban on music, enters the Land of the Dead to find his great- great - grandfather, a legendary singer.",
    genre: "Animation",
    duration: "1h 45m",
    release: 2017,
    rating: [],
    ratingQty: 0,
    director: "Adrian Molina",
    actors: " Anthony Gonzalez ,  Gael García Bernal , Benjamin Bratt, Akemi Yamaguchi, Alanna Ubach ",
    wishlist: false,
  },
];
